import type { Metadata } from 'next';
import './globals.css';
import './embla.css';
import MainNavigation from './components/MainNavigation';
import Footer from './components/Footer';

export const metadata: Metadata = {
  title: 'JAGAesthetic',
  description: 'Generated by JAGAesthetic',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className="flex flex-col min-h-screen">
        <MainNavigation />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
